<?php

namespace App\User\Entity;

use Symfony\Contracts\Translation\TranslatableInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

enum PermissionType: string implements TranslatableInterface {

  case DASHBOARD = 'DASHBOARD';
  case VISIT = 'VISIT';

  case SPECIALIST_LIST = 'SPECIALIST_LIST';
  case SPECIALIST_DETAILS = 'SPECIALIST_DETAILS';
  case SPECIALIST_CREATE = 'SPECIALIST_CREATE';
  case SPECIALIST_UPDATE = 'SPECIALIST_UPDATE';
  case SPECIALIST_DELETE = 'SPECIALIST_DELETE';

  case CLIENT_LIST = 'CLIENT_LIST';
  case CLIENT_DETAILS = 'CLIENT_DETAILS';
  case CLIENT_CREATE = 'CLIENT_CREATE';
  case CLIENT_UPDATE = 'CLIENT_UPDATE';
  case CLIENT_DELETE = 'CLIENT_DELETE';

  case CLIENT_PREFERRED_HOUR_LIST = 'CLIENT_PREFERRED_HOUR_LIST';
  case CLIENT_PREFERRED_HOUR_CREATE = 'CLIENT_PREFERRED_HOUR_CREATE';
  case CLIENT_PREFERRED_HOUR_UPDATE = 'CLIENT_PREFERRED_HOUR_UPDATE';
  case CLIENT_PREFERRED_HOUR_DELETE = 'CLIENT_PREFERRED_HOUR_DELETE';

  case CLIENT_SPECIALIST_LIST = 'CLIENT_SPECIALIST_LIST';
  case CLIENT_SPECIALIST_CREATE = 'CLIENT_SPECIALIST_CREATE';
  case CLIENT_SPECIALIST_UPDATE = 'CLIENT_SPECIALIST_UPDATE';
  case CLIENT_SPECIALIST_DELETE = 'CLIENT_SPECIALIST_DELETE';

  case CLIENT_CONTACT_LIST = 'CLIENT_CONTACT_LIST';
  case CLIENT_CONTACT_CREATE = 'CLIENT_CONTACT_CREATE';
  case CLIENT_CONTACT_UPDATE = 'CLIENT_CONTACT_UPDATE';
  case CLIENT_CONTACT_DELETE = 'CLIENT_CONTACT_DELETE';

  case VISIT_TYPE_LIST = 'VISIT_TYPE_LIST';
  case VISIT_TYPE_DETAILS = 'VISIT_TYPE_DETAILS';
  case VISIT_TYPE_CREATE = 'VISIT_TYPE_CREATE';
  case VISIT_TYPE_UPDATE = 'VISIT_TYPE_UPDATE';
  case VISIT_TYPE_ARCHIVE = 'VISIT_TYPE_ARCHIVE';
  case VISIT_TYPE_UN_ARCHIVE = 'VISIT_TYPE_UN_ARCHIVE';

  case ROLE_LIST = 'ROLE_LIST';
  case ROLE_DETAILS = 'ROLE_DETAILS';
  case ROLE_CREATE = 'ROLE_CREATE';
  case ROLE_UPDATE = 'ROLE_UPDATE';
  case ROLE_ARCHIVE = 'ROLE_ARCHIVE';
  case ROLE_UN_ARCHIVE = 'ROLE_UN_ARCHIVE';

  case COMPANY_DETAILS = 'COMPANY_DETAILS';
  case COMPANY_UPDATE = 'COMPANY_UPDATE';

  public function trans(TranslatorInterface $translator, string $locale = null): string {
    return $translator->trans(strtolower(str_replace('_', '-', $this->value)), locale: $locale);
  }
}